name: Yarn install
description: Install dependencies using Yarn and cache them

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3
      with:
        version: 2025.11.1
    - name: Cache Yarn dependencies
      uses: SonarSource/ci-github-actions/cache@v1
      with:
        path: |
          .yarn
        key: yarn-${{ runner.os }}
    - name: Yarn install dependencies
      shell: bash
      run: |
        CI=false yarn install
