name: Yarn install
description: Install dependencies using Yarn and cache them

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      with:
        version: 2025.9.12
    - name: Cache Yarn dependencies
      uses: SonarSource/ci-github-actions/cache@v1
      with:
        path: |
          .yarn
        key: yarn-${{ runner.os }}
    - name: Yarn install dependencies
      shell: bash
      run: |
        CI=false yarn install
