yarnPath: .yarn/releases/yarn-4.5.1.cjs

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: "https://yarnplugins.com/plugin-echo-execute"

progressBarStyle: simba
